defaults:
  - components@encoder: gcn
  - components/global_pool@readout: mean
  - components@head: mlp
  - optimizer: adamw
  - scheduler: step_lr

_target_: graph_neural_networks.models.GraphLevelLitModule

encoder:
  out_channels: null

head:
  in_channels: ${..encoder.hidden_channels}
  hidden_channels: ${.in_channels}
  num_layers: 2
  dropout: ${..encoder.dropout}
  norm: null

criterion:
  _target_: torch.nn.CrossEntropyLoss

metrics:
  _target_: torchmetrics.MetricCollection
  # since MetricCollection does not recognize OmegaConf containers as their corresponding Python primitives
  # force the conversion of OmegaConf containers to Python primitives
  _convert_: all
  metrics:
    acc:
      _target_: torchmetrics.Accuracy
      task: multiclass
      num_classes: ${hparams.data.num_classes}
