defaults:
  - components@encoder: gcn
  - components/global_pool@readout: mean
  - components@head: mlp
  - optimizer: adamw
  - scheduler: step_lr
  # Metrics depend on the data task, but because of limitations to the interpolation in the defaults list, it is not
  # possible to use the data task value to interpolate which metrics config to use. Therefore, they are to be assigned
  # manually by the user (e.g. in an experiment config).
  - metrics: ???

_target_: graph_neural_networks.models.GraphLevelLitModule
task: ${hparams.data.task}
num_node_features: ${oc.select:hparams.data.num_node_features,0}
num_edge_features: ${oc.select:hparams.data.num_edge_features,0}

encoder:
  out_channels: null

head:
  in_channels: ${..encoder.hidden_channels}
  hidden_channels: ${.in_channels}
  num_layers: 2
  dropout: ${..encoder.dropout}
  norm: null

criterion:
  # Use `CrossEntropyLoss` when task is multiclass, otherwise use `BCEWithLogitsLoss`
  _target_: ${op.ternary:${op:eq,${hparams.data.task},multiclass}, torch.nn.CrossEntropyLoss, torch.nn.BCEWithLogitsLoss}

# Use `torch.float` dtype for target when the criterion is `BCEWithLogitsLoss`, otherwise use `torch.long`
criterion_target_dtype: ${op.ternary:${op:eq,${.criterion._target_},torch.nn.BCEWithLogitsLoss}, torch.float, torch.long}
